SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIOS](
	[USU_UID] [int] IDENTITY(1,1) NOT NULL,
	[USU_UNOMBRE] [varchar](100) NULL,
	[USU_UAPELLIDO_PATERNO] [varchar](100) NULL,
	[USU_UAPELLIDO_MATERNO] [varchar](100) NULL,
	[USU_URUT] [varchar](100) NULL,
	[USU_UMAIL] [varchar](100) NULL,
	[USU_UACTIVO] [binary](1) NULL,
	[USU_UFECHA_CREACION] [datetime] NULL,
	[USU_UFEC_ACTUALIZACION] [datetime] NULL,
	[USU_UFECHA_ULTIMA_CONEXION] [datetime] NULL,
	[USU_UOBSERVACION] [varchar](255) NULL,
	[USU_UFECHA_NACIMIENTO] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USUARIOS] ADD PRIMARY KEY CLUSTERED 
(
	[USU_UID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

